using System.Buffers.Binary;
using System.Runtime.CompilerServices;
using System.Text.Json;
using MemoryPack;
using Microsoft.Extensions.Logging.Abstractions;
using Sharp.Shared.Enums;
using Sharp.Shared.Types;
using Source2Surf.Timer.Modules.Replay;
using Source2Surf.Timer.Shared.Models.Replay;
using Xunit;
using ZstdSharp;

namespace Timer.Tests;

public sealed class ReplayStorageFormatTests
{
    // Captured from the pre-V2 Release assembly, not generated by the codec under test.
    private const string LegacyPayload =
        "AQAAAAAAoD8AACDAAABwQAAASEEAQDPDAAAAAP//////////AQAAAAkAAIACAACABAAAQAgAAAAAIADDAACBQgAAAD0=";
    private const string LegacyCompressedFile =
        "eyJWZXJzaW9uIjoxLCJTdGVhbUlkIjo3NjU2MTE5ODAwMDAwMDAwMSwiVG90YWxGcmFtZXMiOjEsIlByZUZyYW1lIjowLCJQb3N0RnJhbWUiOjAsIlRpbWUiOjEuMjUsIlBsYXllck5hbWUiOiJsZWdhY3ktZml4dHVyZSIsIlN0YWdlVGlja3MiOm51bGx9Cii1L/0gRP0BABQDAQCgPwAAIMAAAHBAAABIQQBAM8P/AQAAAAkAAIACAACABAAAQAggAMMAAIFCAAAAPQQAgQqLy0unBQu0AQ==";

    // Independent 35-byte V2 fixture: count; position and velocity signed int24 values
    // scaled by 32; signed int16 angles; three low-32-bit masks; MoveType.
    private static byte[] CompactPayload => Convert.FromHexString(
        "01000000" +
        "280000B0FFFF780000" +
        "FCEFFF100800010000" +
        "900198E9" +
        "FFFFFFFF0100009002000048" +
        "08");

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public void ReadsHistoricalV1FixturesThroughBothReaders(bool compressed)
    {
        var bytes = compressed
            ? Convert.FromBase64String(LegacyCompressedFile)
            : Wrap(Header(1), Convert.FromBase64String(LegacyPayload));

        AssertFrame(Decode(bytes), LegacyFrame(), 1);

        var path = TempPath();
        try
        {
            File.WriteAllBytes(path, bytes);
            using var decompressor = new Decompressor();
            var loaded = ReplayShared.LoadReplayFromPath(path, 2, 3, 4, decompressor, NullLogger.Instance);
            Assert.True(loaded.HasValue);
            AssertFrame(loaded.Value, LegacyFrame(), 1);
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public void ReadsLegacyHeaderWithoutVersion()
    {
        var bytes = Wrap(new { TotalFrames = 1 }, Convert.FromBase64String(LegacyPayload));
        AssertFrame(Decode(bytes), LegacyFrame(), 1);
    }

    [Fact]
    public void CompactEncodingMatchesIndependentWireFixture()
    {
        var bytes = ReplayShared.SerializeReplay(Header(1), [CompactFrame()]);
        using var decompressor = new Decompressor();
        var raw = decompressor.Unwrap(Payload(bytes)).ToArray();

        using var header = JsonDocument.Parse(bytes.AsMemory(0, Array.IndexOf(bytes, (byte)'\n')));
        Assert.False(header.RootElement.TryGetProperty("FrameSize", out _));
        Assert.Equal(CompactPayload, raw);
        AssertFrame(Decode(Wrap(Header(1) with { Version = 2 }, CompactPayload)), CompactFrame(), 2);
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public void ReadsV2FixtureUsingVersionOnlyThroughBothReaders(bool compressed)
    {
        using var compressor = new Compressor();
        var payload = compressed ? compressor.Wrap(CompactPayload).ToArray() : CompactPayload;
        var bytes = Wrap(Header(1) with { Version = 2 }, payload);

        AssertFrame(Decode(bytes), CompactFrame(), 2);
        var path = TempPath();
        try
        {
            File.WriteAllBytes(path, bytes);
            using var decompressor = new Decompressor();
            var loaded = ReplayShared.LoadReplayFromPath(path, 2, 3, 4, decompressor, NullLogger.Instance);
            Assert.True(loaded.HasValue);
            AssertFrame(loaded.Value, CompactFrame(), 2);
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    public void V2KeepsLowBitsAndDiscardsHighBitsInEachButtonField(int field)
    {
        for (var bit = 0; bit < 64; bit++)
        {
            var buttons = (UserCommandButtons)(1UL << bit);
            var frame = CompactFrame() with
            {
                PressedButtons = field == 0 ? buttons : UserCommandButtons.Attack,
                ChangedButtons = field == 1 ? buttons : UserCommandButtons.Jump,
                ScrollButtons = field == 2 ? buttons : UserCommandButtons.Duck,
            };

            // All low bits keep their original positions; high bits never select V1.
            var bytes = ReplayShared.SerializeReplay(Header(1), [frame]);
            AssertFrame(Decode(bytes), LowButtons(frame), 2);
        }
    }

    [Fact]
    public void AllCurrentlyDefinedButtonsAndTheirCombinationUseCompactFormat()
    {
        var buttons = Enum.GetValues<UserCommandButtons>();
        var all = buttons.Aggregate((UserCommandButtons)0, (current, next) => current | next);
        var frames = buttons.Append(all)
            .Select(value => CompactFrame() with
            {
                PressedButtons = value,
                ChangedButtons = all ^ value,
                ScrollButtons = all,
            })
            .ToArray();

        var loaded = Decode(ReplayShared.SerializeReplay(Header(frames.Length), frames));
        Assert.Equal(2, loaded.Content.Header.Version);
        Assert.Equal(frames.Select(LowButtons), loaded.Content.Frames);
    }

    [Fact]
    public void MixedHighButtonsAreDiscardedWithoutRemappingOrChangingInput()
    {
        var original = CompactFrameWithHighButtons();
        var frames = new[] { original };
        var bytes = ReplayShared.SerializeReplay(Header(1), frames);
        using var decompressor = new Decompressor();

        Assert.Equal(CompactPayload, decompressor.Unwrap(Payload(bytes)).ToArray());
        AssertFrame(Decode(bytes), CompactFrame(), 2);
        Assert.Equal(original, frames[0]);
    }

    [Theory]
    [InlineData(0, 0, false)]
    [InlineData(0, 0, true)]
    [InlineData(3, 0, false)]
    [InlineData(3, 0, true)]
    [InlineData(3, 2, false)]
    [InlineData(3, 2, true)]
    public async Task FileWritesRoundTripBothFormatsAndCompressionModes(int level, int workers, bool fullWidth)
    {
        var frames = new List<ReplayFrameData> { CompactFrame(), CompactFrame(), CompactFrame() };
        // A late spatial overflow selects V1; high buttons alone must stay in V2.
        frames[^1] = fullWidth ? V1FallbackFrame() : CompactFrameWithHighButtons();
        var original = frames.ToArray();
        var expected = fullWidth ? original : frames.Select(LowButtons).ToArray();

        var header = Header(frames.Count) with { Version = 99, PreFrame = 1, PostFrame = 2, StageTicks = [1, 2] };
        var expectedVersion = fullWidth ? 1 : 2;
        var path = TempPath();
        try
        {
            Assert.True(await ReplayShared.WriteReplayToFileAsync(header, path, frames, level, workers, NullLogger.Instance));
            var bytes = File.ReadAllBytes(path);
            var loaded = Decode(bytes);
            Assert.Equal(expectedVersion, loaded.Content.Header.Version);
            Assert.Equal(expected, loaded.Content.Frames);
            Assert.Equal(header.StageTicks, loaded.Content.Header.StageTicks);
            Assert.Equal(header.PreFrame, loaded.Content.Header.PreFrame);
            Assert.Equal(header.PostFrame, loaded.Content.Header.PostFrame);
            Assert.Equal(99, header.Version);

            using var decompressor = new Decompressor();
            var fromDisk = ReplayShared.LoadReplayFromPath(path, 2, 3, 4, decompressor, NullLogger.Instance);
            Assert.True(fromDisk.HasValue);
            Assert.Equal(expected, fromDisk.Value.Content.Frames);
            Assert.Equal(original, frames);
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public void PreservesExistingSpatialQuantizationWithoutMutatingInput(bool fullWidth)
    {
        var original = (fullWidth ? V1FallbackFrame() : CompactFrame()) with
        {
            Origin = new Vector(1.01f, -2.01f, 3.03f),
            Angles = new Vector2D(fullWidth ? 2000.01f : 12.01f, -179.01f),
            Velocity = new Vector(-128.01f, 64.03f, 0.01f),
        };
        var frames = new[] { original };
        var header = Header(1);
        var expected = original with
        {
            Origin = new Vector(1f, -2f, 3.03125f),
            Angles = new Vector2D(fullWidth ? 2000f : 12f, -179f),
            Velocity = new Vector(-128f, 64.03125f, 0f),
        };

        AssertFrame(Decode(ReplayShared.SerializeReplay(header, frames)), expected, fullWidth ? 1 : 2);
        Assert.Equal(original, frames[0]);
        Assert.Equal(1, header.Version);
    }

    [Fact]
    public void CompactFramesUse35BytesInsteadOf64WithoutChangingRuntimeLayout()
    {
        var frames = Enumerable.Repeat(CompactFrame(), 100).ToArray();
        var bytes = ReplayShared.SerializeReplay(Header(frames.Length), frames);
        using var decompressor = new Decompressor();
        var payload = decompressor.Unwrap(Payload(bytes)).ToArray();

        Assert.Equal(64, Unsafe.SizeOf<ReplayFrameData>());
        Assert.Equal(4 + 100 * 64, MemoryPackSerializer.Serialize(frames).Length);
        Assert.Equal(4 + 100 * 35, payload.Length);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(3)]
    [InlineData(4)]
    [InlineData(5)]
    [InlineData(6)]
    [InlineData(7)]
    public void SignedFixedPointEndpointsRoundTripForEveryComponent(int component)
    {
        var minimum = component < 6 ? -262144f : -1024f;
        var maximum = component < 6 ? 262143.96875f : 1023.96875f;
        var frames = new[] { minimum, -1f / 32f, 0f, 1f / 32f, maximum }
            .Select(value => WithComponent(CompactFrame(), component, value))
            .ToArray();

        var loaded = Decode(ReplayShared.SerializeReplay(Header(frames.Length), frames));
        Assert.Equal(2, loaded.Content.Header.Version);
        Assert.Equal(frames, loaded.Content.Frames.ToArray());
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(3)]
    [InlineData(4)]
    [InlineData(5)]
    [InlineData(6)]
    [InlineData(7)]
    public void SpatialOverflowInAnyComponentFallsBackWithoutClamping(int component)
    {
        var belowMinimum = component < 6 ? -262144.03125f : -1024.03125f;
        var aboveMaximum = component < 6 ? 262144f : 1024f;
        foreach (var value in new[] { belowMinimum, aboveMaximum })
        {
            var frames = new[] { CompactFrame(), WithComponent(CompactFrame(), component, value) };
            var loaded = Decode(ReplayShared.SerializeReplay(Header(frames.Length), frames));
            Assert.Equal(1, loaded.Content.Header.Version);
            Assert.Equal(frames, loaded.Content.Frames.ToArray());
        }
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(3)]
    [InlineData(4)]
    [InlineData(5)]
    [InlineData(6)]
    [InlineData(7)]
    public void NonFiniteAndExtremeValuesFallBackWithoutOverflowOrBitLoss(int component)
    {
        var values = new[]
        {
            float.MaxValue, float.MinValue, float.PositiveInfinity, float.NegativeInfinity,
            BitConverter.Int32BitsToSingle(0x7FC12345),
        };
        foreach (var value in values)
        {
            var frame = WithComponent(CompactFrame(), component, value);
            var loaded = Decode(ReplayShared.SerializeReplay(Header(1), [frame]));
            Assert.Equal(1, loaded.Content.Header.Version);
            var actual = Assert.Single(loaded.Content.Frames);
            // ModSharp vector equality uses a numeric tolerance and is not reflexive for infinity.
            // Compare every scalar's raw bits to verify the stronger storage guarantee instead.
            for (var scalar = 0; scalar < 8; scalar++)
                Assert.Equal(BitConverter.SingleToInt32Bits(GetComponent(frame, scalar)),
                             BitConverter.SingleToInt32Bits(GetComponent(actual, scalar)));
            Assert.Equal(frame.PressedButtons, actual.PressedButtons);
            Assert.Equal(frame.ChangedButtons, actual.ChangedButtons);
            Assert.Equal(frame.ScrollButtons, actual.ScrollButtons);
            Assert.Equal(frame.MoveType, actual.MoveType);
        }
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(3)]
    [InlineData(4)]
    [InlineData(5)]
    [InlineData(6)]
    [InlineData(7)]
    public void FixedPointKeepsRoundToEvenForPositiveAndNegativeTies(int component)
    {
        var values = new[] { 0.015625f, 0.046875f, -0.015625f, -0.046875f, MathF.BitIncrement(0.015625f) };
        var rounded = new[] { 0f, 0.0625f, 0f, -0.0625f, 0.03125f };
        var frames = values.Select(value => WithComponent(CompactFrame(), component, value)).ToArray();
        var expected = rounded.Select(value => WithComponent(CompactFrame(), component, value)).ToArray();
        var loaded = Decode(ReplayShared.SerializeReplay(Header(frames.Length), frames));

        Assert.Equal(2, loaded.Content.Header.Version);
        Assert.Equal(expected, loaded.Content.Frames.ToArray());
    }

    [Theory]
    [InlineData(-1024.0078125f, -1024f, 2)]
    [InlineData(-1024.015625f, -1024f, 2)]
    [InlineData(1023.9765625f, 1023.96875f, 2)]
    [InlineData(1023.984375f, 1024f, 1)]
    public void AngleRangeIsCheckedAfterRounding(float value, float expected, int version)
    {
        var original = WithComponent(CompactFrame(), 6, value);
        var loaded = Decode(ReplayShared.SerializeReplay(Header(1), [original]));
        AssertFrame(loaded, WithComponent(CompactFrame(), 6, expected), version);
    }

    [Theory]
    [InlineData(0, 0)]
    [InlineData(3, 0)]
    [InlineData(0, 3)]
    [InlineData(3, 3)]
    [InlineData(0, 7)]
    [InlineData(3, 7)]
    public async Task SpatialFallbackAlsoAppliesToLocalWrites(int compressionLevel, int component)
    {
        var frame = WithComponent(CompactFrame(), component, 300000f);
        var path = TempPath();
        try
        {
            Assert.True(await ReplayShared.WriteReplayToFileAsync(Header(1), path, [frame], compressionLevel, 0, NullLogger.Instance));
            var loaded = Decode(File.ReadAllBytes(path));
            AssertFrame(loaded, frame, 1);
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public void ManyDistinctFramesKeepTheExistingQuantizationAndFieldOrder()
    {
        var random = new Random(12531);
        var frames = new ReplayFrameData[2048];
        var expected = new ReplayFrameData[frames.Length];
        for (var i = 0; i < frames.Length; i++)
        {
            var frame = CompactFrame() with { MoveType = (MoveType)(i & 0xFF) };
            var rounded = frame;
            for (var component = 0; component < 8; component++)
            {
                var range = component < 6 ? 200000f : 180f;
                var value = (random.NextSingle() * 2f - 1f) * range;
                frame = WithComponent(frame, component, value);
                // Reference the pre-existing float quantization rather than the new integer codec.
                rounded = WithComponent(rounded, component, MathF.Round(value * 32f) / 32f);
            }
            frames[i] = frame;
            expected[i] = rounded;
        }

        var loaded = Decode(ReplayShared.SerializeReplay(Header(frames.Length), frames));
        Assert.Equal(2, loaded.Content.Header.Version);
        Assert.Equal(expected, loaded.Content.Frames.ToArray());
    }

    [Fact]
    public void EmptyReplayRoundTrips()
    {
        var loaded = Decode(ReplayShared.SerializeReplay(Header(0), []));
        Assert.Equal(2, loaded.Content.Header.Version);
        Assert.Empty(loaded.Content.Frames);
    }

    [Theory]
    [InlineData(-1)]
    [InlineData(0)]
    [InlineData(3)]
    [InlineData(int.MaxValue)]
    public void RejectsUnsupportedFormatVersions(int version)
    {
        var bytes = Wrap(Header(1) with { Version = version }, CompactPayload);
        Assert.Null(ReplayShared.DeserializeReplay(bytes, 2, 3, 4, NullLogger.Instance));
    }

    [Fact]
    public void RejectsWrongVersionTruncationTrailingBytesAndImpossibleCounts()
    {
        var compactHeader = Header(1) with { Version = 2 };
        Assert.Null(ReplayShared.DeserializeReplay(Wrap(compactHeader, Convert.FromBase64String(LegacyPayload)), 0, 0, 0, NullLogger.Instance));
        Assert.Null(ReplayShared.DeserializeReplay(Wrap(Header(1), CompactPayload), 0, 0, 0, NullLogger.Instance));

        for (var length = 0; length < CompactPayload.Length; length++)
            Assert.Null(ReplayShared.DeserializeReplay(Wrap(compactHeader, CompactPayload[..length]), 0, 0, 0, NullLogger.Instance));

        foreach (var invalid in new[]
        {
            CompactPayload.Concat(new byte[] { 0 }).ToArray(),
            CompactPayload.Concat(new byte[10]).ToArray(), // V2 requires exactly 35 bytes per frame
            Convert.FromHexString("FFFFFF7F"), // int.MaxValue frames without data
            Convert.FromHexString("FEFFFFFF"), // invalid negative count
            Convert.FromHexString("FFFFFFFF"), // null frame collection
        })
        {
            Assert.Null(ReplayShared.DeserializeReplay(Wrap(compactHeader, invalid), 0, 0, 0, NullLogger.Instance));
        }
    }

    [Theory]
    [InlineData(1)]
    [InlineData(2)]
    public void NullArraysAreRejectedForEverySupportedLayout(int version)
    {
        var header = Header(0) with { Version = version };
        Assert.Null(ReplayShared.DeserializeReplay(Wrap(header, Convert.FromHexString("FFFFFFFF")), 0, 0, 0, NullLogger.Instance));
        Assert.Empty(Decode(Wrap(header, Convert.FromHexString("00000000"))).Content.Frames);
    }

    [Theory]
    [InlineData(1, 64)]
    [InlineData(2, 35)]
    public void DirectDecoderAllocatesOnlyTheFinalArrayAndDoesNotRetainInput(int version, int frameSize)
    {
        const int count = 8192;
        var fixture = version == 1 ? Convert.FromBase64String(LegacyPayload) : CompactPayload;
        var payload = new byte[sizeof(int) + count * frameSize];
        BinaryPrimitives.WriteInt32LittleEndian(payload, count);
        for (var i = 0; i < count; i++)
            fixture.AsSpan(sizeof(int)).CopyTo(payload.AsSpan(sizeof(int) + i * frameSize));

        _ = ReplayFrameStorage.Deserialize(payload, version);
        var before = GC.GetAllocatedBytesForCurrentThread();
        var frames = ReplayFrameStorage.Deserialize(payload, version)!;
        var allocated = GC.GetAllocatedBytesForCurrentThread() - before;

        // No intermediate array proportional to the frame count may be allocated.
        Assert.InRange(allocated, count * 64L, count * 64L + 1024);
        Array.Fill(payload, (byte)0xCC);
        var expected = version == 1 ? LegacyFrame() : CompactFrame();
        Assert.Equal(count, frames.Length);
        Assert.All(frames, frame => Assert.Equal(expected, frame));
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public void EncodingIntoCallerBufferDoesNotAllocateAnIntermediateFrameArray(bool fullWidth)
    {
        var frames = Enumerable.Repeat(fullWidth ? V1FallbackFrame() : CompactFrame(), 8192).ToArray();
        var output = new byte[sizeof(int) + frames.Length * (fullWidth ? 64 : 35)];
        for (var i = 0; i < 4; i++)
            new ReplayFrameStorage(frames).Serialize(output);

        var before = GC.GetAllocatedBytesForCurrentThread();
        var storage = new ReplayFrameStorage(frames);
        storage.Serialize(output);
        var allocated = GC.GetAllocatedBytesForCurrentThread() - before;

        // Allow bounded runtime/test-runner initialization, far below one full frame array.
        Assert.InRange(allocated, 0, 16 * 1024);
        Assert.Equal(frames, ReplayFrameStorage.Deserialize(output, storage.Version));
        if (fullWidth)
            Assert.Equal(MemoryPackSerializer.Serialize(frames), output);
    }

    [Theory]
    [InlineData(0, false)]
    [InlineData(1, false)]
    [InlineData(1872, false)]
    [InlineData(1873, false)]
    [InlineData(8192, false)]
    [InlineData(1, true)]
    [InlineData(1023, true)]
    [InlineData(1024, true)]
    [InlineData(8192, true)]
    public async Task AsyncEncoderWritesBoundedChunksWithExactlyOneArrayHeader(int count, bool fullWidth)
    {
        var frames = Enumerable.Range(0, count)
            .Select(i => (fullWidth ? V1FallbackFrame() : CompactFrame()) with
            {
                Origin = new Vector(i / 32f, -i / 32f, (i % 100) / 32f),
            }).ToArray();
        var storage = new ReplayFrameStorage(frames);
        await using var stream = new DelayedRecordingStream();
        await storage.SerializeAsync(stream);
        var payload = stream.ToArray();

        Assert.InRange(stream.LargestWrite, 4, 64 * 1024);
        Assert.Equal(sizeof(int) + count * storage.FrameSize, payload.Length);
        Assert.Equal(count, BinaryPrimitives.ReadInt32LittleEndian(payload));
        Assert.Equal(frames, ReplayFrameStorage.Deserialize(payload, storage.Version));
        if (fullWidth)
            Assert.Equal(MemoryPackSerializer.Serialize(frames), payload);
    }

    [Theory]
    [InlineData(0, false)]
    [InlineData(0, true)]
    [InlineData(3, false)]
    [InlineData(3, true)]
    public async Task LargeFilesAndHeadersRoundTripWithoutRetainingPooledBuffers(int level, bool fullWidth)
    {
        var frames = Enumerable.Range(0, 8192)
            .Select(i => (fullWidth ? V1FallbackFrame() : CompactFrame()) with
            {
                Origin = new Vector(i / 32f, -i / 32f, i % 16),
            }).ToArray();
        var header = Header(frames.Length) with { StageTicks = Enumerable.Range(0, 2048).ToList() };
        var firstPath = TempPath();
        var secondPath = TempPath();
        try
        {
            Assert.True(await ReplayShared.WriteReplayToFileAsync(header, firstPath, frames, level, 0, NullLogger.Instance));
            var bytes = File.ReadAllBytes(firstPath);
            Assert.True(Array.IndexOf(bytes, (byte)'\n') > 4096);
            var memoryLoaded = Decode(bytes);
            using var decompressor = new Decompressor();
            var diskLoaded = ReplayShared.LoadReplayFromPath(firstPath, 2, 3, 4, decompressor, NullLogger.Instance);
            Assert.True(diskLoaded.HasValue);

            // Load different contents of the same size to exercise reuse of both byte pools.
            var replacement = Enumerable.Repeat(fullWidth ? V1FallbackFrame() : CompactFrame(), frames.Length).ToArray();
            Assert.True(await ReplayShared.WriteReplayToFileAsync(header, secondPath, replacement, level, 0, NullLogger.Instance));
            _ = Decode(File.ReadAllBytes(secondPath));
            var second = ReplayShared.LoadReplayFromPath(secondPath, 2, 3, 4, decompressor, NullLogger.Instance);
            Assert.True(second.HasValue);
            Assert.Equal(replacement, second.Value.Content.Frames);

            Array.Fill(bytes, (byte)0xCC);
            Assert.Equal(frames, memoryLoaded.Content.Frames);
            Assert.Equal(frames, diskLoaded.Value.Content.Frames);
            Assert.Equal(header.StageTicks, diskLoaded.Value.Content.Header.StageTicks);
        }
        finally
        {
            File.Delete(firstPath);
            File.Delete(secondPath);
        }
    }

    [Fact]
    public void UploadResultOwnsItsBufferAcrossSubsequentSaves()
    {
        var frames = Enumerable.Repeat(CompactFrame(), 8192).ToArray();
        var first = ReplayShared.SerializeReplay(Header(frames.Length), frames);
        var savedBytes = first.ToArray();
        Array.Fill(frames, CompactFrame() with { Origin = new Vector(12, 34, 56) });
        _ = ReplayShared.SerializeReplay(Header(frames.Length), frames);

        Assert.Equal(savedBytes, first);
        Assert.All(Decode(first).Content.Frames, frame => Assert.Equal(CompactFrame(), frame));
    }

    [Fact]
    public void PooledFileReaderClosesHandleBeforeBackingUpCorruptFiles()
    {
        var path = TempPath();
        var invalid = new byte[] { 1, 2, 3, 4, 5 };
        try
        {
            File.WriteAllBytes(path, invalid);
            using var decompressor = new Decompressor();
            Assert.Null(ReplayShared.LoadReplayFromPath(path, 2, 3, 4, decompressor, NullLogger.Instance));
            Assert.False(File.Exists(path));
            Assert.Equal(invalid, File.ReadAllBytes(path + ".corrupt"));

            File.WriteAllBytes(path, ReplayShared.SerializeReplay(Header(1), [CompactFrame()]));
            var loaded = ReplayShared.LoadReplayFromPath(path, 2, 3, 4, decompressor, NullLogger.Instance);
            Assert.True(loaded.HasValue);
            AssertFrame(loaded.Value, CompactFrame(), 2);
        }
        finally
        {
            File.Delete(path);
            File.Delete(path + ".corrupt");
        }
    }

    private sealed class DelayedRecordingStream : MemoryStream
    {
        public int LargestWrite { get; private set; }

        public override async ValueTask WriteAsync(ReadOnlyMemory<byte> buffer, CancellationToken cancellationToken = default)
        {
            // Force the encoder to preserve its borrowed block across a genuinely asynchronous write.
            await Task.Yield();
            cancellationToken.ThrowIfCancellationRequested();
            LargestWrite = Math.Max(LargestWrite, buffer.Length);
            Write(buffer.Span);
        }
    }

    private static ReplayFrameData WithComponent(ReplayFrameData frame, int component, float value)
        => component switch
        {
            0 => frame with { Origin = new Vector(value, frame.Origin.Y, frame.Origin.Z) },
            1 => frame with { Origin = new Vector(frame.Origin.X, value, frame.Origin.Z) },
            2 => frame with { Origin = new Vector(frame.Origin.X, frame.Origin.Y, value) },
            3 => frame with { Velocity = new Vector(value, frame.Velocity.Y, frame.Velocity.Z) },
            4 => frame with { Velocity = new Vector(frame.Velocity.X, value, frame.Velocity.Z) },
            5 => frame with { Velocity = new Vector(frame.Velocity.X, frame.Velocity.Y, value) },
            6 => frame with { Angles = new Vector2D(value, frame.Angles.Y) },
            7 => frame with { Angles = new Vector2D(frame.Angles.X, value) },
            _ => throw new ArgumentOutOfRangeException(nameof(component)),
        };

    private static float GetComponent(ReplayFrameData frame, int component)
        => component switch
        {
            0 => frame.Origin.X, 1 => frame.Origin.Y, 2 => frame.Origin.Z,
            3 => frame.Velocity.X, 4 => frame.Velocity.Y, 5 => frame.Velocity.Z,
            6 => frame.Angles.X, 7 => frame.Angles.Y,
            _ => throw new ArgumentOutOfRangeException(nameof(component)),
        };

    private static ReplayLoadResult Decode(byte[] bytes)
    {
        var loaded = ReplayShared.DeserializeReplay(bytes, 2, 3, 4, NullLogger.Instance);
        Assert.True(loaded.HasValue);
        return loaded.Value;
    }

    private static void AssertFrame(ReplayLoadResult loaded, ReplayFrameData expected, int version)
    {
        Assert.Equal(2, loaded.Style);
        Assert.Equal(3, loaded.Track);
        Assert.Equal(4, loaded.Stage);
        Assert.Equal(version, loaded.Content.Header.Version);
        Assert.Equal(expected, Assert.Single(loaded.Content.Frames));
    }

    private static ReplayFrameData CompactFrame()
        => LegacyFrame() with
        {
            PressedButtons = (UserCommandButtons)0xFFFFFFFFUL,
            ChangedButtons = (UserCommandButtons)0x90000001UL,
            ScrollButtons = (UserCommandButtons)0x48000002UL,
        };

    private static ReplayFrameData CompactFrameWithHighButtons()
        => CompactFrame() with
        {
            PressedButtons = (UserCommandButtons)ulong.MaxValue,
            ChangedButtons = (UserCommandButtons)0xFEDCBA9890000001UL,
            ScrollButtons = (UserCommandButtons)0xFFFFFFFF48000002UL,
        };

    private static ReplayFrameData V1FallbackFrame()
        => LegacyFrame() with { Angles = new Vector2D(2000f, -179.25f) };

    private static ReplayFrameData LowButtons(ReplayFrameData frame)
        => frame with
        {
            PressedButtons = (UserCommandButtons)((ulong)frame.PressedButtons & 0xFFFFFFFFUL),
            ChangedButtons = (UserCommandButtons)((ulong)frame.ChangedButtons & 0xFFFFFFFFUL),
            ScrollButtons = (UserCommandButtons)((ulong)frame.ScrollButtons & 0xFFFFFFFFUL),
        };

    private static ReplayFrameData LegacyFrame()
        => new()
        {
            Origin = new Vector(1.25f, -2.5f, 3.75f),
            Angles = new Vector2D(12.5f, -179.25f),
            PressedButtons = (UserCommandButtons)ulong.MaxValue,
            ChangedButtons = (UserCommandButtons)0x8000000900000001UL,
            ScrollButtons = (UserCommandButtons)0x4000000480000002UL,
            MoveType = (MoveType)8,
            Velocity = new Vector(-128.125f, 64.5f, 0.03125f),
        };

    private static ReplayFileHeader Header(int frameCount)
        => new()
        {
            SteamId = 76561198000000001,
            TotalFrames = frameCount,
            Time = 1.25f,
            PlayerName = "legacy-fixture",
        };

    private static byte[] Payload(byte[] bytes)
        => bytes[(Array.IndexOf(bytes, (byte)ReplayShared.HeaderFrameSeparator) + 1)..];

    private static byte[] Wrap<T>(T header, byte[] payload)
    {
        using var stream = new MemoryStream();
        JsonSerializer.Serialize(stream, header);
        stream.WriteByte((byte)ReplayShared.HeaderFrameSeparator);
        stream.Write(payload);
        return stream.ToArray();
    }

    private static string TempPath() => Path.Combine(Path.GetTempPath(), $"timer-replay-format-{Guid.NewGuid():N}.replay");
}
